DROP TRIGGER order_friends_pairs;
DROP TRIGGER cities_trigger;
DROP SEQUENCE cities_seq;
DROP TRIGGER programs_trigger;
DROP SEQUENCE programs_seq;
DROP TABLE friends;
DROP TABLE cities cascade constraints;
DROP TABLE user_current_cities;
DROP TABLE user_hometown_cities;
DROP TABLE messages;
DROP TABLE education;
DROP TABLE participants;
DROP TABLE user_events;
DROP TABLE photos cascade constraints;
DROP TABLE tags;
ALTER TABLE albums DROP constraint albums_cover_photo_id;
ALTER TABLE photos DROP constraint photos_albums_id;
DROP TABLE albums cascade constraints; 
DROP TABLE programs cascade constraints;
DROP TABLE users;